# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-5WnpNssCJc4VyZWWyiZOAZeQoWtlm4

# **Đọc thư viện**
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

"""# **Đọc và mô tả file dữ liệu**"""

data=pd.read_csv('/content/Loan_Default.csv')
print(data.info())

print(data.describe())

"""# **Cleanning data**"""

drop_cols = [
    'ID',                     # Không có ý nghĩa do không có liên hệ với status
    'year',                   # Có một năm duy nhất là 2019 nên bỏ qua
    'Interest_rate_spread',   # Missing data quá nhiều (36639)
    'property_value',         # Missing data quá nhiều (15098)
    'Upfront_charges',        # Missing data quá nhiều (39642)
    'dtir1'                   # dtir1 (Debt-to-Income ratio) = debt / income (Giữ hai cái kia và bỏ cái dtir 1 vì dễ bị đa cộng tuyến)
]
data.drop(columns=drop_cols, inplace=True, errors='ignore')

for col in data.columns:
    if data[col].dtype == 'object':
        data[col].fillna(data[col].mode()[0], inplace=True)
    else:
        data[col].fillna(data[col].mean(), inplace=True)

before = data.shape[0]
data.drop_duplicates(inplace=True)
print(f"Đã loại {before - data.shape[0]} dòng trùng, còn lại {data.shape[0]}.")

"""# **Normalization**"""

if 'age' in data.columns:
    data['age'] = data['age'].replace({
        '35-44': 39.5, '25-34': 29.5, '55-64': 59.5,
        '45-54': 49.5, '65-74': 69.5, '>74': 80, '<25': 20
    })

data['rate_of_interest']=data['rate_of_interest']/1200

"""# **Heatmap tương quan theo biến định lượng**"""

plt.figure(figsize=(10, 8))
sns.heatmap(data.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Heatmap of Numerical Features")
plt.show()

"""# **Countplot các biến định tính theo Status**"""

categorical_cols = [col for col in data.columns if data[col].dtype == 'object']
palette = sns.color_palette("coolwarm", n_colors=2)
for col in categorical_cols:
    plt.figure(figsize=(6, 4))
    sns.countplot(data=data, x=col, hue='Status', palette=palette)
    plt.title(f"Countplot of {col} by Status", fontsize=12, fontweight='bold')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

from google.colab import files
data.to_csv('dataset_clean.csv', index=False)
files.download('dataset_clean.csv')